language: node_js
node_js:
  - 'node'
cache:
  - yarn
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: s3
  access_key_id: AKIAIJQFM5L2LQPC73DA
  secret_access_key: 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
  skip_cleanup: true
  local_dir: build
  default_text_charset: 'utf-8'
  bucket: 'astrotim'
  region: us-east
